infra:
  environment: production
  server-id: paper-1
  require-service-registry: true

redis:
  host: localhost
  port: 6379
  ssl: false
  password: ""
  timeout-ms: 5000

database:
  host: localhost
  port: 3306
  database: crown
  username: crown
  password: crown
  pool-size: 10
  properties:
    useSSL: false
    characterEncoding: utf8
